# MerphisOS Calamares - GRUB configuration
# Bootloader settings

grubCfg: "/boot/grub/grub.cfg"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubMkconfigCfg: "/etc/default/grub"
grubReuseTimeout: false
grubReplaceTimeout: 5

# OS Prober for dual-boot
osProber:
    enabled: false  # privacy - disable by default

# Default boot entry
defaultEntry: "MerphisOS"
